// src/components/Footer.vue
<template>
  <div :class="`text-center ${this.$store.state.darkModeClass}`">
      <div>
          {{
          `"We must make sure that chess will not be like a dead language;
          very interesting but for a very small group."`
          }}
      </div>
      <div>a Byron J-Mil Hall production</div>
      <div>
          <a href="mailto:selmachessapp@gmail.com" target="_top">
              selmachessapp@gmail.com
          </a>
      </div>
  </div>
</template>

<script>
export default {

};
</script>

<style>

</style>

// src/components/subcomponents/Footer.jsx
import React from 'react';

import '../../styles/subcomponents/Footer.css'

const Footer = () => (
  <div className="footer-container pt-3">
    <div className="text-center">&quot;We must make sure that chess will not be like a dead language; very intersting but for a very small group.&quot;</div>
    <div className="text-center">a Byron J-Mil Hall production</div>
  </div>
);

export default Footer;
